---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
```

```{r}
library(tidyverse)
```

```{r}
library(dplyr)
```

```{r}
library(janitor)
```


```{r}
install.packages("here")
```

```{r}
install.packages("readxl")
```

```{r}
library(readxl)
```


Task 4 - Decathlon Data
```{r}
candy_2015 <- read_excel("boing-boing-candy-2015.xlsx")
candy_2015

```

```{r}
head(candy_2015)
dim(candy_2015)
names(dim(candy_2015))
names(candy_2015)
```

```{r}
view(candy_2015)
```


```{r}
candy_2016 <- read_excel("boing-boing-candy-2016.xlsx")
candy_2016
```

```{r}
candy_2017 <- read_excel("boing-boing-candy-2017.xlsx")
candy_2017
```

# select and clean columns by position
```{r}
candy_2015_clean <- candy_2015 %>%
select(c(2:96))

```

```{r}
candy_2016_clean <- candy_2016 %>%
select(c(2:5,7:106))
```

```{r}
candy_2017_clean <- candy_2017 %>%
select(c(2:5,7:109))
```

# clean the column names
```{r}
candy_2015_clean <- clean_names(candy_2015_clean)
candy_2016_clean <- clean_names(candy_2016_clean)
candy_2017_clean <- clean_names(candy_2017_clean)

```

# check data
```{r}
#glimpse(candy_2015_clean)
#glimpse(candy_2016_clean)
#glimpse(candy_2017_clean)

#Data type
typeof(candy_2015_clean)
typeof(candy_2016_clean)
typeof(candy_2017_clean)


```

# Year column cleaned
```{r}
candy_2015_clean$year = "2015"
candy_2016_clean$year = "2016"
candy_2017_clean$year = "2017"

```

# Missing columns in 2015 with no values 
```{r}
candy_2015_clean$country = ''
candy_2015_clean$gender = ''

```

# Reorder 2015 columns
```{r}
candy_2015_clean_reordered <- candy_2015_clean[, c(2, 98, 1, 97, 3:96)]
#view(candy_2015_clean_reordered)
```

#View cleaned data
```{r}
view(candy_2015_clean_reordered)
view(candy_2016_clean)
view(candy_2017_clean)

```


```{r}
dim(candy_2015_clean_reordered)
dim(candy_2016_clean)
dim(candy_2017_clean)

```

# pivot long on 3 data
```{r}
candy_2015_clean_long <- pivot_longer(data = candy_2015_clean_reordered[,1:98],
cols = 5:97,
names_to = "column_candy",
values_to = "value")

```

```{r}
candy_2016_clean_long <- pivot_longer(data = candy_2016_clean[,1:105],
cols = 5:104,
names_to = "column_candy",
values_to = "value")


```

```{r}
candy_2017_clean_long <- pivot_longer(data = candy_2017_clean[,1:108],
cols = 5:107,
names_to = "column_candy",
values_to = "value")

```

```{r}
view(candy_2015_clean_long)
```

```{r}
view(candy_2016_clean_long)
```

```{r}
view(candy_2017_clean_long)

```


# Join all 2015, 2016, 2017 into 1 dataset

```{r}
candy_all_years_clean <- rbind(candy_2015_clean_long,
                               candy_2016_clean_long,
                               candy_2017_clean_long)
view(candy_all_years_clean)
```
















